### PR TITLE
Added link for grok101

### PR DESCRIPTION
**Pull request by vinodpahuja**

### CODE REVIEW

**Comment by jsvd** [comment]
Thank you for the contribution, are you the author of this website? what is the problem it solves when comparing to grokdebugger and grokconstructor?

**Comment by vinodpahuja** [comment]
Yes, I have created this site on top of grokconstrcutor to provide a modern user experience.

- instead of plain html with reload, it uses SPA and ajax to make the job quick
- instead of an embedded server side UI and , I am converting it to API based backend
- it will provide more accessible and configurable pattern library

In short grok101 = grokconstrctor + regex101
GitHub : https://github.com/grok101/grok101

Currently it is an MVP but making it available early to the public will enable feedback from the user on what is more important than what looks more tempting.

Further I am for suggestions.

**Comment by jsvd** [comment]
I see, if it provides the same functionality with a reworked UX I'd suggest seeing how the community reacts to it and its changes over the existing site before guiding our users towards it. The existing entries came from community suggestions due to broad adoption and usage.
Another suggestion is to reach out to the original author about the changes, perhaps they can be merged upstream?

Thanks again for your work, I'm closing the issue now.

**Comment by vinodpahuja** [comment]
Thanks for the suggestions, I will surely take feedback for the community and try to connect the original author for his point of view.

**Pull request closed without merging**
