### PR TITLE
Add patterns defintion option

### PR DESCRIPTION
**Pull request by suyograo**
Add option to define patterns inline in the filter using `pattern_definitions` configuration.

### CODE REVIEW

**Comment by suyograo** [comment]
hmm not sure why the tests are failing on travis. they pass locally :/

**Comment by suyograo** [comment]
@talevy tests are fixed now.

**Comment by talevy** [comment]
@suyograo are they? I don't see any changes. I re-ran the task

**Comment by suyograo** [comment]
@talevy I published a new version of `logstash-core-plugin-api` which tracks 5.2.1. That fixed it.

**Comment by talevy** [comment]
@suyograo ah, re-ran locally. LGTM

**Comment by suyograo** [comment]
Travis is now failing because of S3 related issues. Will wait for that dust to settle down before I merge.

**Pull request merged**
